services:
  homehub-samba:
    container_name: homehub-samba
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    build:
      context: ../samba
    hostname: dc1
    env_file:
      - ../../.env
    ports:
      # - "53:53/tcp"
      # - "53:53/udp"
      - "88:88/tcp"
      - "88:88/udp"
      - "135:135"
      - "389:389"
      - "445:445"
      - "464:464"
      - "636:636"
    volumes:
      # - samba-db:/var/lib/samba
      # - samba-cache:/var/cache/samba
      # - samba-config:/etc/samba
      - /opt/homehub/samba/data:/var/lib/samba
      - /opt/homehub/samba/cache:/var/cache/samba
      - /opt/homehub/samba/config:/etc/samba

volumes:
  samba-db:
  samba-cache:
  samba-config: